---
distros:
  - el8
release_branches:
  master: [ "ovirt-master" ]
stages:
  - build-artifacts:
      substages:
        - ansible-core
        - ansible
  - check-patch:
      substages:
        - ansible-core
        - ansible
  - build-artifacts-manual:
      substages:
        - ansible-core
        - ansible
