namespace: "@NAMESPACE@"
name: "@NAME@"
version: 2.1.0
authors:
    - Martin Necas <mnecas@redhat.com>
license:
    - Apache-2.0
    - GPL-3.0-or-later
tags:
    - collection
    - infrastructure
    - linux
    - cloud
    - virtualization
readme: README.md
repository: https://github.com/ovirt/ovirt-ansible-collection
issues: https://github.com/ovirt/ovirt-ansible-collection/issues
description: The oVirt Ansible Collection.
homepage: https://www.ovirt.org/
