namespace: "ovirt"
name: "ovirt"
version: 1.1.4
authors:
    - Martin Necas <mnecas@redhat.com>
license:
    - Apache-2.0
    - GPL-3.0-or-later
tags:
    - collection
readme: README.md
repository: https://github.com/ovirt/ovirt-ansible-collection
description: The oVirt ansible collection.
homepage: https://www.ovirt.org/
