namespace: "@NAMESPACE@"
name: "@NAME@"
version: 1.2.4
authors:
    - Martin Necas <mnecas@redhat.com>
license:
    - Apache-2.0
    - GPL-3.0-or-later
tags:
    - collection
readme: README.md
repository: https://github.com/ovirt/ovirt-ansible-collection
description: The oVirt Ansible Collection.
homepage: https://www.ovirt.org/
