---
version: 1
dependencies:
  system: bindep.txt
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend:
    - RUN pip3 install --upgrade pip setuptools
    - RUN dnf copr enable -y ovirt/ovirt-master-snapshot
    - RUN dnf install -y ovirt-release-master
    - RUN dnf install ovirt-ansible-collection -y
  append:
    - RUN ls -la /usr/share/ansible/collections/ansible_collections/
