---
- name: Setup ovirt repositories, deploy oVirt Engine and then upgrade it
  hosts: engine
  vars_files:
    - passwords.yml
  vars:
    ovirt_engine_setup_product_type: "ovirt"
    ovirt_engine_setup_version: "{{ ovirt_engine_setup_version }}"
    ovirt_engine_setup_organization: "example.com"
    ovirt_engine_setup_configure_iso_domain: true
    ovirt_engine_setup_firewall_manager:
    ovirt_repositories_ovirt_release_rpm: "{{ ovirt_repositories_ovirt_release_rpm }}"
  roles:
    - role: ovirt.ovirt.repositories
    - role: ovirt.ovirt.engine_setup
      ovirt_engine_setup_update_packages: true
      ovirt_engine_setup_answer_file_path: "answerfile_{{ ovirt_engine_setup_version }}_upgrade.txt.j2"
