---
- name: Search VLAN devices
  set_fact:
    is_vlan: "{{ nic_if.stdout == 'vlan' }}"
  when: nic_if.stdout.find('vlan') != -1
  with_items:
    - "{{ interface_types.results }}"
  loop_control:
    loop_var: nic_if
  register: vlan_list
- debug: var=vlan_list
- import_tasks: validate_vlan_name.yml
- import_tasks: validate_vlan_bond_mode.yml
- name: Generate list of all unsupported VLAN devices
  set_fact:
    invalid_vlan_if: "{{ bad_vlan_bond_list + bad_vlan_names_list }}"
- debug: var=invalid_vlan_if
