---
- include_tasks: auth_sso.yml
- name: Fetch host facts
  ovirt_host_info:
    pattern: name={{ he_host_name }}
    auth: "{{ ovirt_auth }}"
  register: host_result
  until: host_result is succeeded and host_result.ovirt_hosts|length >= 1
  retries: 50
  delay: 10
- name: iSCSI discover
  ovirt_host:
    auth: "{{ ovirt_auth }}"
    state: iscsidiscover
    name: "{{ he_host_name }}"
    iscsi:
      address: "{{ he_iscsi_portal_addr }}"
      port: "{{ he_iscsi_portal_port }}"
      username: "{{ he_iscsi_discover_username | default(omit) }}"
      password: "{{ he_iscsi_discover_password | default(omit) }}"
  register: otopi_iscsi_targets
# TODO: perform an iSCSI logout when viable, see:
# https://bugzilla.redhat.com/show_bug.cgi?id=1535951
# https://github.com/ansible/ansible/issues/35039
...
