---
- name: Configure Apache
  block:
    - name: Replace OIDCProviderMetadataURL value
      ansible.builtin.replace:
        path: /etc/httpd/conf.d/internalsso-openidc.conf
        regexp: '(^\s+OIDCProviderMetadataURL https:\/\/).+(\/ovirt-engine.*)'
        replace: '\g<1>{{ he_host_address }}:6900\g<2>'
    - name: Replace OIDCRedirectURI value
      ansible.builtin.replace:
        path: /etc/httpd/conf.d/internalsso-openidc.conf
        regexp: '(^\s+OIDCRedirectURI https:\/\/).+(\/ovirt-engine.*)'
        replace: '\g<1>{{ he_host_address }}:6900\g<2>'
    - name: Replace OIDCDefaultURL value
      ansible.builtin.replace:
        path: /etc/httpd/conf.d/internalsso-openidc.conf
        regexp: '(^\s+OIDCDefaultURL https:\/\/).+(\/ovirt-engine.*)'
        replace: '\g<1>{{ he_host_address }}:6900\g<2>'
    - name: Replace OIDCOAuthIntrospectionEndpoint value
      ansible.builtin.replace:
        path: /etc/httpd/conf.d/internalsso-openidc.conf
        regexp: '(^\s+OIDCOAuthIntrospectionEndpoint https:\/\/).+(\/ovirt-engine.*)'
        replace: '\g<1>{{ he_host_address }}:6900\g<2>'
- name: Configure Keycloak
  block:
    - name: Copy keycloak_he_pause_host.sh
      ansible.builtin.copy:
        src: /usr/share/ansible/collections/ansible_collections/ovirt/ovirt/roles/hosted_engine_setup/files/keycloak_he_pause_host.sh
        dest: /tmp/keycloak_he_pause_host.sh
        mode: '0644'
    - name: Run keycloak_he_pause_host.sh
      shell: /bin/bash /tmp/keycloak_he_pause_host.sh
      environment:
        KEYCLOAK_URL: "https://{{ he_fqdn }}/ovirt-engine-auth"
        HOST_FQDN: "{{ he_host_name }}"
        PASSWORD: "{{ he_admin_password }}"
- name: Restart httpd service
  ansible.builtin.service:
    name: httpd
    state: restarted
