- block:
    - name: Fetch invalid storage domain for remove
      ovirt_storage_domain_info:
          pattern:  name={{ storage['dr_' + dr_source_map + '_name'] }} and {{ dr_inactive_domain_search }}
          auth: "{{ ovirt_auth }}"
      register: storage_domain_info

    - name: Remove invalid storage domain
      include_tasks: remove_domain_process.yml
      vars:
          sd: "{{ sd }}"
      with_items:
          - "{{ storage_domain_info.ovirt_storage_domains }}"
      when: (not only_master and not sd.master) or (only_master and sd.master)
      loop_control:
          loop_var: sd
  ignore_errors: "{{ dr_ignore_error_clean }}"
  tags:
      - fail_back
      - clean_engine
