---
- name: Remove valid storage domain main block
  block:
    - name: Fetch active storage domain for remove
      ovirt_storage_domain_info:
        pattern: >
          name={{ storage['dr_' + dr_source_map + '_name'] }} and
            datacenter={{ storage['dr_' + dr_source_map + '_dc_name'] }} and {{ dr_active_domain_search }}
        auth: "{{ ovirt_auth }}"
      register: storage_domain_info_active

    - name: Fetch maintenance storage domain for remove
      ovirt_storage_domain_info:
        pattern: >
          name={{ storage['dr_' + dr_source_map + '_name'] }} and
            datacenter={{ storage['dr_' + dr_source_map + '_dc_name'] }} and {{ dr_maintenance_domain_search }}
        auth: "{{ ovirt_auth }}"
      register: storage_domain_info_maintenance

    - name: Fetch detached storage domain for remove
      ovirt_storage_domain_info:
        pattern: >
           name={{ storage['dr_' + dr_source_map + '_name'] }} and
            datacenter={{ storage['dr_' + dr_source_map + '_dc_name'] }} and {{ dr_active_domain_search }} 
        auth: "{{ ovirt_auth }}"
      register: storage_domain_info_active

    - name: Remove valid storage domain
      include_tasks: remove_domain_process.yml
      vars:
        sd: "{{ sd }}"
      with_items:
        - "{{ storage_domain_info_active.ovirt_storage_domains }}"
        - "{{ storage_domain_info_maintenance.ovirt_storage_domains }}"
        - "{{ storage_domain_info_detached.ovirt_storage_domains }}"
      when: (not only_master and not sd.master) or (only_master and sd.master)
      loop_control:
        loop_var: sd
  ignore_errors: "{{ dr_ignore_error_clean }}"
  tags:
    - fail_back
    - clean_engine
