---
- name: Add storage domain main block
  ignore_errors: "{{ dr_ignore_error_recover }}"
  tags:
    - fail_over
    - fail_back
  block:
    - name: Fetch available hosts in data center
      ovirt.ovirt.ovirt_host_info:
        pattern: "status=up and datacenter={{ storage['dr_' + dr_target_host + '_dc_name'] }}"
        auth: "{{ ovirt_auth }}"
      register: host_info

    - name: Check for available hosts block
      block:
        - name: "Check for available hosts"
          ansible.builtin.fail:
            msg: "No hosts available"
          when: host_info.ovirt_hosts.0 is undefined

    - name: Add storage domain block
      when: host_info.ovirt_hosts.0 is defined
      block:
        - name: Add storage domain if NFS
          ansible.builtin.include_tasks: add_nfs_domain.yml
          with_items:
            - "{{ storage }}"
          when: "storage.dr_domain_type == 'nfs'"
          loop_control:
            loop_var: nfs_storage

        - name: Add storage domain if Gluster
          ansible.builtin.include_tasks: add_glusterfs_domain.yml
          with_items:
            - "{{ storage }}"
          when: "storage.dr_domain_type == 'glusterfs'"
          loop_control:
            loop_var: gluster_storage

        - name: Add storage domain if POSIX
          ansible.builtin.include_tasks: add_posixfs_domain.yml
          with_items:
            - "{{ storage }}"
          when: "storage.dr_domain_type == 'posixfs'"
          loop_control:
            loop_var: posix_storage

        - name: Add storage domain if iSCSI
          ansible.builtin.include_tasks: add_iscsi_domain.yml
          with_items:
            - "{{ storage }}"
          when: "storage.dr_domain_type == 'iscsi'"
          loop_control:
            loop_var: iscsi_storage

        - name: Add storage domain if FCP
          ansible.builtin.include_tasks: add_fcp_domain.yml
          with_items:
            - "{{ storage }}"
          when: "storage.dr_domain_type == 'fcp'"
          loop_control:
            loop_var: fcp_storage
