---
# vars:
#  progress: % complete
#  cluster_name: (if available) what cluster is being worked on
#  host_name: (if avaiable) what host in the cluster is being worked on
#  description: what part of the process is actually done

- block:
  - name: Log progress as an event
    vars:
      message:
        - "Cluster upgrade progress: {{ progress }}%"
        - "{{ ', Cluster: ' + cluster_name if (cluster_name is defined and cluster_name) else '' }}"
        - "{{ ', Host: ' + host_name if (host_name is defined and host_name) else '' }}"
        - " [{{ description }}]"
    ovirt_event:
      auth: "{{ ovirt_auth }}"
      state: present
      severity: normal
      custom_id: "{{ 2147483647 | random | int }}"
      origin: "cluster_upgrade"
      description: "{{ message | join('') }}"
      cluster: "{{ cluster_id | default(omit) }}"
