---
- name: oVirt remove stale LUN
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    # Contains encrypted `engine_password` varibale using ansible-vault
    - passwords.yml

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_user: root
    ansible_ssh_private_key_file: /etc/pki/ovirt-engine/keys/engine_id_rsa
    
    engine_fqdn: ovirt.example.com
    engine_user: admin@internal

    data_center: default
    lun_wwid: 36001405a77a1ee25cbf4439b7ddd2062 36001405ddefe8392bb8443e89bde4b40

  roles:
    - remove_stale_lun
  collections:
    - @NAMESPACE@.@NAME@
